version: '3'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        networks:
            - laravel-net

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/data/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/data/certbot/www:/var/www/certbot
        depends_on:
            - php
            - certbot
        networks:
            - laravel-net

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/data/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"


networks:
    laravel-net: